### ISSUE TITLE
Floating point precision issues for Typescript

### ISSUE THREAD

**Issue by zongweil** [tspoke/typescript-open-location-code#3]
Hello from the main Open Location Code repo!

We're currently working on fixing floating point precision issues with the various implementations (see [here](https://github.com/google/open-location-code/issues/307)). For the implementations not directly in the main repo, we're asking for the owners to update their code accordingly. Would you be able to do the following when you get a chance?

1) Run the new test cases in test_data/encoding.csv.
2) If they fail, fix your implementation to properly handle the floating point precision issues. I'll post again when we have a commit that you can use for reference.

**Comment by jan25** [comment]
https://github.com/google/open-location-code/pull/305 This is a PR for JS changes in main repo which could be used as a reference. I'll try to test/open PR in this repo when i get a chance

**Comment by tspoke** [comment]
Thanks @jan25 for your help, I won't have time to get this done in the next weeks so feel free to make a PR and I will happily take a look at it.

Sorry for the delay !

**Comment by QuanTumli** [comment]
I just opened a Draft PR for this issue. Maybe @jan25 has an idea why the Validity Tests are failing:  https://github.com/tspoke/typescript-open-location-code/pull/4

**Comment by jan25** [comment]
@QuanTumli Hi! added a small comment to the PR. We might want to make a tiny change to this library to make pass the test cases

**Comment by jan25** [comment]
Also, It'd be nice to get a new release out after this issue is resolved?

**Comment by tspoke** [comment]
- I just pushed a new version to npm : **1.5.0**
- I updated the devDependencies too and upgrade TS to 3.7.5.
- The tag is in sync with the package.

Thanks for your time!! 🥇
